#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "PS2DEMLandscapeSplineLibrary.generated.h"

UCLASS()
class PS2DEMIMPORTER_API UPS2DEMLandscapeSplineLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:
    /** Convert selected imported route actors into persistent Landscape Splines. */
    UFUNCTION(BlueprintCallable, Category = "PS2DEM|Landscape")
    static bool ConvertSelectedRoutesToLandscapeSplines(bool bShowConfirmation = true);

    /** Return a compact summary used by diagnostics and unattended verification. */
    UFUNCTION(BlueprintPure, Category = "PS2DEM|Landscape")
    static FString GetGeneratedLandscapeSplineSummary();

    /** Assign the Static Mesh selected in the Content Browser to one generated route type. */
    UFUNCTION(BlueprintCallable, Category = "PS2DEM|Landscape")
    static void AssignSelectedMeshToGeneratedLandscapeSplines(const FString& RouteType);

    /** Remove only Landscape Spline points and segments generated by PS2DEM. */
    UFUNCTION(BlueprintCallable, Category = "PS2DEM|Landscape")
    static void RemoveGeneratedLandscapeSplines();
};
